@startuml US04-SD-partial-get-locomotive-types-list
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US04 - Get Locomotive Types List - Partial Sequence Diagram

participant ":CreateScenarioUI" as UI
participant ":CreateScenarioController" as CTRL
participant ":LocomotiveTypeRepository" as LOCOREPO
participant "locomotiveTypeList\n:List<LocomotiveType>" as LOCOTYPELIST

UI -> CTRL : getLocomotiveTypeList()
activate CTRL
    group Get Locomotive Types List
    CTRL -> LOCOREPO : getAllLocomotiveTypes()
    activate LOCOREPO
        LOCOREPO --> CTRL : locomotiveTypeList
    deactivate LOCOREPO
    end group

    CTRL --> UI : locomotiveTypeList

deactivate CTRL
@enduml