@startuml US08-SD-partial-calculate-path-cost
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US08 - Calculate Path and Cost - Partial Sequence Diagram

participant ":BuildRailwayLineUI" as UI
participant ":BuildRailwayLineController" as CTRL
participant "startStation:Station" as START_STATION
participant "endStation:Station" as END_STATION
participant ":PathFinderService" as PATHFINDER
participant "path:Path" as PATH
participant ":RailwayLineService" as LINESERVICE
participant "cost:Money" as COST

UI -> CTRL : calculatePathAndCost(startStation, endStation)
activate CTRL
    group Calculate Path and Cost
    CTRL -> PATHFINDER : findPath(startStation, endStation)
    activate PATHFINDER
        PATHFINDER --> CTRL : path
    deactivate PATHFINDER

    CTRL -> LINESERVICE : calculateConstructionCost(path)
    activate LINESERVICE
        LINESERVICE --> CTRL : cost
    deactivate LINESERVICE
    end group
    CTRL --> UI : path, cost
deactivate CTRL
@enduml
